module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fbf8ff",
        "primary-fixed": "#e1e0ff",
        "inverse-surface": "#242770",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "tertiary-container": "#370e00",
        "on-tertiary-fixed": "#370e00",
        "surface-dim": "#d7d7ff",
        background: "#fbf8ff",
        "on-error": "#ffffff",
        "surface-variant": "#e1e0ff",
        "on-surface-variant": "#464651",
        "outline-variant": "#c7c5d2",
        "on-secondary-container": "#b6baff",
        secondary: "#0001c0",
        "on-primary-fixed-variant": "#3b3f87",
        "on-tertiary-container": "#e65300",
        "on-secondary-fixed-variant": "#0000ef",
        "surface-container": "#eeecff",
        primary: "#000000",
        "on-primary": "#ffffff",
        outline: "#777682",
        "surface-bright": "#fbf8ff",
        "secondary-fixed": "#e0e0ff",
        "surface-container-low": "#f5f2ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#00006e",
        "on-surface": "#0c0d5b",
        tertiary: "#000000",
        "on-primary-fixed": "#0c0d5b",
        "on-background": "#0c0d5b",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#ffb599",
        "inverse-primary": "#c0c1ff",
        "inverse-on-surface": "#f1efff",
        "primary-container": "#0c0d5b",
        "surface-tint": "#5357a1",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-high": "#e7e6ff",
        "on-primary-container": "#797dca",
        "surface-container-highest": "#e1e0ff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbce",
        "on-tertiary-fixed-variant": "#802a00",
        "secondary-container": "#080cff",
        "secondary-fixed-dim": "#bec2ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
};
